server:
  port: 0

spring:
  application:
    name: server
  config:
    import: 'configserver:'
  cloud:
    openfeign:
      lazy-attributes-resolution: true
    config:
      discovery:
        enabled: true
        serviceId: config-server
      fail-fast: false
      retry:
        useRandomPolicy: true
        max-interval: 6000
        max-attempts: 3

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/