explore-with-me:
  datetime:
    format: "yyyy-MM-dd HH:mm:ss"
  main:
    datetime:
      format: "yyyy-MM-dd HH:mm:ss"
  stat:
    datetime:
      format: "yyyy-MM-dd HH:mm:ss"

logging:
  level:
    org:
      springframework:
        web: INFO
        validation: INFO
      hibernate:
        SQL: INFO

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/main_db
    username: postgres
    password: "12345"